### ISSUE TITLE
Supporting biber at conda-forge

### ISSUE THREAD

**Issue by anjos** [plk/biber#485]
Hello,

With the maturity of [tectonic](https://tectonic-typesetting.github.io/en-US/), and its availability at [conda-forge](https://conda-forge.org) and the conda packaging ecosystem, it looks like we're near the point where we can actually dream of building compact and portable LaTeX compilation systems.

Unfortunately, [due to an issue opened for some time now](https://github.com/tectonic-typesetting/tectonic/issues/893), there seems to exist a strict interdependence between Tectonic and Biber.  A precise version of Biber and Tectonic must exist on the same environment so BibLaTeX can be used.

I'd like to include the support for Biber at conda-forge.  For such a thing, I was checking out the build instructions for this package (even though I have almost no practice with perl). Looking at [how others have bundled it](https://gitlab.archlinux.org/archlinux/packaging/packages/biber/-/blob/main/PKGBUILD?ref_type=heads), there seems to be a substantial number of build/runtime dependencies (I counted at least 30) that would need packaging in conda-forge, before biber itself can be ported.

I was thinking that a faster way to implement this support in distributions in general could be to re-use pre-built binaries from Biber's release page.  As I understand, it is possible to run this application from a bundle that auto-unwraps and has no other runtime requirements.

Currently no binary packages are available through the release page.  Are there any plans to support this?  Any community tips on how to approach this problem would be extremely helpful.  Thanks!

**Comment by plk** [comment]
The pre-built "binaries" are all on Sourceforge here:

https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/

**Comment by njzjz** [comment]
> there seems to be a substantial number of build/runtime dependencies (I counted at least 30) that would need packaging in conda-forge, before biber itself can be ported.

I think this is not a real problem, as most packages are very similar. I can contribute them to conda-forge as much as I can.

**Comment by anjos** [comment]
@njzjz: thanks for your help.

You'll find a lot of those recipes are available here: https://github.com/danielnachun/recipe_staging, thanks to @danielnachun.

If you don't mind, please add myself @anjos and @danielnachun as co-maintainers on your PRs.

**Comment by danielnachun** [comment]
A couple of suggestions to make this go more smoothly:
- Make sure that recipes that are pure Perl without any compiled code are `noarch: generic` - this saves us a lot of headache because the package only needs to be built on Linux.
- When submitting recipes, I would strongly recommend making separate PRs for `noarch: generic` and native recipes.  It is much easier to review recipes when they are organized like that, because you know you can ignore Windows failures for `noarch: generic`, while for native recipes Windows either needs to work or be skipped.
- I'd also actually recommend not submitting groups of recipes together that depend on each other.  While you can get things to build in the staged-recipes CI, when the feedstocks are created, the recipes that depend on other recipes will fail to render and you'll have to ask the conda-forge bot to rerender the feedstock.  I find this to be tedious and annoying, so I try to build up to the recipes with the most new dependencies in the last PRs.
- I usually submit no more than 5 recipes at a time in a single PR because it's easier to track down failures

**Comment by danielnachun** [comment]
I have some exciting news - I was able to package `biber` on my own channel as "proof of concept" of what is needed for it to get into conda-forge.  You can test out the package now with `pixi global install -c dnachun -c conda-forge biber`.  I will post the full dependency tree in a bit which will annotate what Perl modules are coming from my channel (meaning they were in bioconda or missing altogether) and which are already in conda-forge.  @anjos I currently use `biber` through MacTeX so I'm not sure what should be done to test it with `tectonic`, but let me know if you find any problems.

**Comment by anjos** [comment]
This is great, thanks a lot for the effort, @danielnachun! [Tectonic is picky w.r.t. to the biber version](https://github.com/tectonic-typesetting/tectonic/issues/893) it wants to use.  The latest version (0.15.x) requires biber 2.17.  I saw you packaged 2.20 (the very latest).  Would it be possible to backport the recipe to 2.17?  That would make it work for Tectonic-based workflows.

**Comment by danielnachun** [comment]
The backport is done!  `pixi global install -c dnachun -c conda-forge biber=2.17` should get you the compatible version.  

Also, I don't know if this has been pointed out to the `tectonic` developers yet, but `biber` 2.17 is more than two years old at this point, so it would be great if they could eventually update to work with a newer version.  Though it's my eventual hope that `tectonic` can implement the functionality of tools like `biber`, `asymptote`, `latexmk` etc. in Rust to avoid these challenges with dependency management.

**Comment by anjos** [comment]
That was a very quick reaction, thanks @danielnachun!  I just tested my working environment against your channel.  The following pixi environment works like a charm, and compiles my test LaTeX files w/o issues:

```toml
[project]
name = "test"
channels = ["dnachun", "conda-forge"]
platforms = ["osx-arm64"]

[dependencies]
tectonic = "0.15"
biber = { version = "2.17", channel = "dnachun" }
```

Adding `linux-64` to the platforms gets me the following error though:

```
  × failed to solve the conda requirements of 'default' 'linux-64'                              
  ╰─▶ Cannot solve the request because of: The following packages are incompatible                  
      ├─ tectonic ==0.15 can be installed with any of the following options:
      │  └─ tectonic 0.15.0 would require
      │     └─ icu >=73.2,<74.0a0, which can be installed with any of the following options:
      │        └─ icu 73.2
      └─ biber ==2.17 cannot be installed because there are no viable options:
         └─ biber 2.17 would require
            └─ perl-xml-libxml *, which cannot be installed because there are no viable options:
               └─ perl-xml-libxml 2.207 would require
                  └─ libxml2 >=2.13.5,<3.0a0, which cannot be installed because there are no viable options:
                     ├─ libxml2 2.13.5 | 2.13.5 would constrain
                     │  └─ icu <0.0a0, which conflicts with any installable versions previously reported
                     └─ libxml2 2.13.5 | 2.13.5 would require
                        └─ icu >=75.1,<76.0a0, which cannot be installed because there are no viable options:
                           └─ icu 75.1, which conflicts with the versions reported above.
```

**Comment by danielnachun** [comment]
I think the only fix for that error is to get https://github.com/conda-forge/tectonic-feedstock/pull/72 merged, but it seems to have failed.  I will push a copy of `tectonic` to my channel that is built against the latest dependencies so you can run the test environment on `linux-64`.  Then can make a PR to fix whatever is failing in the feedstock.

**Comment by danielnachun** [comment]
I've added `tectonic` to my channel.  The following commands work without error on `linux-64`:
```
pixi global install -c dnachun -c conda-forge tectonic
pixi global install -c dnachun -c conda-forge --environment tectonic biber=2.17
```
I think that should get you a `tectonic` installation with `biber` 2.17.

**Comment by anjos** [comment]
Thanks - that worked well 🚀, with your version of tectonic, on both osx-arm64 and linux-64.  I'll try to test later on linux-aarch64 (if available).

**Comment by anjos** [comment]
@danielnachun: The pixi resolve on linux-aarch64 is blocked with:

```
...
      └─ biber 2.17 would require
         └─ perl-autovivification *, for which no candidates were found.
```

However, everything else works 100% and I see no reason why it would not also work for linux-aarch64 at this point!

**Comment by danielnachun** [comment]
There are definitely a number of "native" Perl modules with embedded C code in the dependency tree that are not built for `linux-aarch64`.  I will see if I can manually build these in a VM, since I have an Apple Silicon Mac that can easily run `linux-aarch64` VMs.  

I haven't actually worked out a good system yet for getting `linux-aarch64` into my personal CI setup - probably I'll have to set up emulation, because cross-compilation is a pain and GitHub Actions still does not provide native `linux-aarch64`, despite having been requested for years!

**Comment by anjos** [comment]
Right, emulation indeed seems to work better on CF builds as well.  Please do not bother with linux-aarch64.

I'd rather focus on pushing all this work to conda-forge.  One could then trigger linux-aarch64 migration across the various packages. I can do it if you add me as co-maintainer.

**Comment by danielnachun** [comment]
Agreed, I have a large number of Perl packages now that I can submit now, and I can focus on the ones needed for `biber` first.

**Comment by anjos** [comment]
Hello @danielnachun, I wonder if you had the time to start looking into this?  Do not hesitate to ask for help!

**Comment by danielnachun** [comment]
Here is the parts of the dependency tree that will either need to be submitted from my recipes, or will need changes in their existing conda-forge feedstock:
- [ ] perl-autovivification - `conda-forge` - native, needs other arches
- [ ] perl-business-ismn - `dnachun` -  noarch
    - [ ] perl-tie-cycle - `dnachun` - noarch
- [ ] perl-class-accessor - `dnachun` - noarch
- [ ] perl-data-compare - `dnachun` - noarch
    - [ ] perl-clone - `conda-forge` - native, needs other arches
        - [ ] perl-b-cow - `conda-forge` - native, needs other arches
    - [ ] perl-file-find-rule - `dnachun` - noarch
        - [ ] perl-text-glob - `dnachun` - noarch
- [ ] perl-data-dump - `dnachun` - noarch
- [ ] perl-data-uniqid - `dnachun` - noarch
- [ ] perl-datetime-calendar-julian - `dnachun`
    - [ ] perl-datetime - `dnachun` - native
        - [ ] perl-datetime-locale - `dnachun` - noarch
            - [ ] perl-dist-checkconflicts - `conda-forge` - needs to be noarch
                - [ ] perl-module-runtime - `conda-forge` - needs to be noarch
            - [ ] perl-file-sharedir - `dnachun` - noarch
                - [ ] perl-class-inspector - `dnachun` - noarch
                - [ ] perl-file-sharedir-install - `dnachun` - noarch
            - [ ] perl-file-sharedir-install - `dnachun` - noarch
            - [ ] perl-ipc-system-simple - `conda-forge` - needs to be noarch
            - [ ] perl-namespace-autoclean - `dnachun` - noarch
                - [ ] perl-b-hooks-endofscope - `conda-forge` - native, needs other arches
                    - [ ] perl-module-implementation - `conda-forge` - needs to be noarch
                        - [ ] perl-module-runtime - `conda-forge` - needs to be noarch
                        - [ ] perl-try-tiny - `conda-forge` - needs to be noarch
                    - [ ] perl-sub-exporter-progressive - `conda-forge` - needs to be noarch
                    - [ ] perl-variable-magic - `conda-forge` - native, needs other arches
                - [ ] perl-namespace-clean - `conda-forge` - needs to be noarch
                    - [ ] perl-b-hooks-endofscope - `conda-forge` - native, needs other arches
                      - see above
                    - [ ] perl-package-stash - `conda-forge` - needs to be noarch
                        - [ ] perl-module-implementation - `conda-forge` - needs to be noarch
                            - see above
                - [ ] perl-sub-identify - `conda-forge` - native, needs other arches
            - [ ] perl-params-validationcompiler - `dnachun` - native
                - [ ] perl-eval-closure - `conda-forge` - native, needs other arches
                - [ ] perl-exception-class - `conda-forge` - needs to be noarch
                    - [ ] perl-class-data-inheritable - `conda-forge` - needs to be noarch
                    - [ ] perl-devel-stacktrace - `conda-forge` - needs to be noarch
                - [ ] perl-specio - `dnachun` - noarch
                    - [ ] perl-devel-stacktrace - `conda-forge` - needs to be noarch
                    - [ ] perl-eval-closure - `conda-forge` - native, needs other arches
                    - [ ] perl-module-runtime - `conda-forge` - needs to be noarch
                    - [ ] perl-mro-compat - `conda-forge` - needs to be noarch
                    - [ ] perl-role-tiny - `conda-forge` - needs to be noarch
                    - [ ] perl-sub-quote - `conda-forge` - needs to be noarch
                    - [ ] perl-test-fatal - `conda-forge` - needs to be noarch
                        - [ ] perl-try-tiny - `conda-forge` - needs to be noarch
                    - [ ] perl-try-tiny - `conda-forge` - needs to be noarch
                - [ ] perl-test2-suite - `dnachun` - noarch
                    - [ ] perl-term-table - dnachun - noarch
            - [ ] perl-sub-identify - `conda-forge` - native, needs other arches
            - [ ] perl-test-file-sharedir - `dnachun` - noarch
        - [ ] perl-datetime-timezone - `dnachun` - noarch
            - [ ] perl-class-singleton - `dnachun` - noarch
            - [ ] perl-module-runtime - `conda-forge` - needs to be noarch
            - [ ] perl-namespace-autoclean - `dnachun` - noarch
                - see above
            - [ ] perl-params-validationcompiler - `dnachun` - native
                - see above
            - [ ] perl-sub-identify - `conda-forge` - native, needs other arches
            - [ ] perl-try-tiny - `conda-forge` - needs to be noarch
        - [ ] perl-specio - `dnachun` - noarch
            - see above
        - [ ] perl-sub-identify - `conda-forge` - native, needs other arches
        - [ ] perl-test2-suite - `dnachun` - noarch
            - see above
        - [ ] perl-try-tiny - `conda-forge` - needs to be noarch
- [ ] perl-datetime-format-builder - `dnachun`
    - [ ] perl-datetime - `dnachun` - native
        - see above
    - [ ] perl-datetime-format-strptime - `dnachun` - noarch
        - [ ] perl-datetime - `dnachun` - native
            - see above
        - [ ] perl-datetime-locale - `dnachun` - noarch
            - see above
        - [ ] perl-datetime-timezone - `dnachun` - noarch
            - see above
        - [ ] perl-params-validationcompiler - `dnachun` - native
            - see above
        - [ ] perl-specio - `dnachun` - noarch
            - see above
        - [ ] perl-sub-identify - `conda-forge` - native, needs other arches
        - [ ] perl-try-tiny - `conda-forge` - needs to be noarch
- [ ] perl-encode-eucjpascii - `dnachun` - native
- [ ] perl-encode-hanextra - `dnachun` - native
- [ ] perl-encode-jis2k - `dnachun` - native
- [ ] perl-encode-locale - `dnachun` - noarch
- [ ] perl-file-slurper - `dnachun` - noarch
- [ ] perl-io-string - `dnachun` - noarch
- [ ] perl-ipc-run3 - `dnachun` - noarch
- [ ] perl-libwww-perl - `dnachun` - noarch
    - [ ] perl-encode-locale - `dnachun` - noarch
    - [ ] perl-file-listing - `dnachun` - noarch
        - [ ] perl-http-date - `dnachun` - noarch
    - [ ] perl-html-parser - `dnachun` - native
        - [ ] perl-html-tagset - `dnachun` - noarch
        - [ ] perl-http-message - `dnachun` - noarch
            - [ ] perl-clone - `conda-forge` - native, needs other arches
            - [ ] perl-encode-locale - `dnachun` - noarch
            - [ ] perl-http-date - `dnachun` - noarch
            - [ ] perl-io-html - `dnachun` - noarch
            - [ ] perl-lwp-mediatypes - `dnachun` - noarch
            - [ ] perl-uri - `conda-forge` - needs to be noarch
        - [ ] perl-uri - `conda-forge` - needs to be noarch
    - [ ] perl-lwp-mediatypes - `dnachun` - noarch
    - [ ] perl-net-http - `dnachun` - noarch
        - [ ] perl-io-socket-ssl - `conda-forge`- no changes needed
            - [ ] perl-net-ssleay - `conda-forge` - native, needs other arches
        - [ ] perl-uri - `conda-forge` - needs to be noarch
    - [ ] perl-test-requiresinternet - `dnachun` - noarch
    - [ ] perl-try-tiny - `conda-forge` - needs to be noarch
    - [ ] perl-www-robotrules - `dnachun`- noarch
        - [ ] perl-uri - `conda-forge` - needs to be noarch
- [ ] perl-lingua-translit - `dnachun` - noarch
- [ ] perl-list-allutils - `dnachun` - noarch
    - [ ] perl-list-someutils - `dnachun` - noarch
        - [ ] perl-module-implementation - `conda-forge` - needs to be noarch
            - see above
    - [ ] perl-list-utilsby - `dnachun` - noarch
    - [ ] perl-scalar-list-utils - `conda-forge` - native, needs other arches
- [ ] perl-list-moreutils - `dnachun` - noarch
    - [ ] perl-list-moreutils-xs - `dnachun` - native
- [ ] perl-list-moreutils-xs - `dnachun` - native
- [ ] perl-lwp-protocol-https - `dnachun`- noarch
    - [ ] perl-io-socket-ssl - `conda-forge` - no changes needed
        - see above
    - [ ] perl-libwww-perl - `dnachun` - noarch
        - see above
- [ ] perl-mozilla-ca - `dnachun` - noarch
- [ ] perl-parse-recdescent - `dnachun` - native
- [ ] perl-perlio-utf8_strict - `dnachun` - native
- [ ] perl-sort-key - `conda-forge` - native, needs other arches
- [ ] perl-storable - `conda-forge` - native, needs other arches
- [ ] perl-text-bibtex - `dnachun` - native
    - [ ] perl-config-autoconf - `dnachun` - native
    - [ ] perl-extutils-libbuilder - `dnachun` - native
        - [ ] perl-module-build - `conda-forge` - needs to be noarch
    - [ ] perl-module-build - `conda-forge` - needs to be noarch
- [ ] perl-text-csv_xs - `dnachun` - native
- [ ] perl-text-roman - `dnachun` - noarch
- [ ] perl-unicode-collate - `dnachun` - native
- [ ] perl-unicode-linebreak - `dnachun` - native
- [ ] perl-uri - `conda-forge` - needs to be noarch
- [ ] perl-xml-libxml - `dnachun` - native
    - [ ] perl-alien-libxml2 - `dnachun` - native
        - [ ] perl-alien-build - `dnachun` - native
            - [ ] perl-ffi-checklib - `dnachun` - noarch
                - [ ] perl-test2-suite - `dnachun` - noarch
                    - see above
            - [ ] perl-test2-suite - `dnachun` - noarch
                - see above
        - [ ] perl-test2-suite - `dnachun` - noarch
            - see above
- [ ] perl-xml-libxml-simple - `dnachun` - noarch
    - [ ] perl-xml-libxml - `dnachun` - native
        - see above
- [ ] perl-xml-libxslt - `dnachun` - native
    - [ ] perl-xml-libxml- `dnachun` - noarch
        - see above
- [ ] perl-xml-writer - `dnachun` - noarch

**Comment by danielnachun** [comment]
I'm now going list off the set of PRs that need to made for new submissions to `staged-recipes`  and to `conda-forge` to make the necessary updates of existing feedstocks.  I will be making submissions to `staged-recipes` in groups of no more than 5, keeping `noarch` and native recipes separate and only submitting groups of recipes that don't depend on each other.

# New submissions
## Stage 1
### noarch
- [ ] perl-class-accessor, perl-class-inspector, perl-class-singleton, perl-data-dump, perl-data-uniqid
- [ ] perl-encode-locale, perl-file-sharedir-install, perl-file-slurper, perl-http-date, perl-io-html
- [ ] perl-io-string, perl-ipc-run3, perl-linguag-translit, perl-list-utilsby, perl-lwp-mediatypes
- [ ] perl-mozilla-ca, perl-namespace-autoclean, perl-specio, perl-tie-cycle, perl-text-glob
- [ ] perl-term-table, perl-test-file-sharedir, perl-test-requiresinternet, perl-text-roman, perl-xml-writer
### native
- [ ] perl-config-autoconf, perl-encode-eucjpascii, perl-encode-hanextra, perl-encode-jis2k, perl-extutils-libbuild
- [ ] perl-list-moreutils-xs, perl-parse-recdescent, perl-perlio-utf8_strict
- [ ] perl-text-csv_xs, perl-unicode-collate, perl-unicode-linebreak
## Stage 2
### noarch
- [ ] perl-business-ismn, perl-file-find-rule, perl-file-sharedir, perl-http-message
- [ ] perl-list-allutils, perl-list-moreutils, perl-test2-suite
### native
- [ ] perl-text-bibtex
## Stage 3
### noarch
- [ ] perl-data-compare, perl-ffi-checklib
### native
- [ ] perl-html-parser, perl-params-validationcompiler
## Stage 4
### noarch
- [ ] perl-datetime-locale, perl-datetime-timezone, perl-libwww-perl
### native
- [ ] perl-alien-build
## Stage 5
### native
- [ ] perl-alien-libxml2, perl-datetime
## Stage 6
### noarch
- [ ] perl-datetime-calendar-julian, perl-datetime-format-builder
### native
- [ ] perl-xml-libxml
## Stage 7
### noarch
- [ ] perl-xml-libxml-simple
### native
- [ ] perl-xml-libxslt

**Comment by njzjz** [comment]
> needs other arches

You could add all of them to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/arch_rebuild.txt and the bot will submit PRs automatically.

**Comment by danielnachun** [comment]
Yes, though we also need to add them to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt as well to get `osx-arm64`.  I had paused on using the automatic migrator for `arch_rebuild` for a while because it was still using Travis for, which is no longer functioning, but I think it has now been switched to default to Azure emulation instead.

Unfortunately there is not a "make `noarch`" equivalent, which means we'll have to manually do those I guess.  Also, I'll note here that we may need to update the versions of some of those feedstocks as well.  I'm not sure if we have autotick-bot support for CPAN - if not, adding this would also be very helpful for keeping these feedstocks up to date.

**Comment by anjos** [comment]
Thanks, @danielnachun: I'll try to start this week end with the no arch builds in the prescribed order.

**Comment by anjos** [comment]
@danielnachun: regarding this issue, CF is still not producing "native" biber packages, as you are following up, mostly depending on [perl build changes to be merged](https://github.com/conda-forge/perl-feedstock/pull/68).  Meanwhile, tectonic was updated to version 0.16.9, which broke biber compatibility again.  Can you point me to the sources of `dnachun/biber` on conda-forge or update [that package on your channel](https://anaconda.org/channels/dnachun/packages/biber/overview), so I portable work environment is possible once more?
